export const GET_POKEMONS = 'GET_POKEMONS';
export const DELETE_POKEMON = 'DELETE_POKEMONS';
export const ADD_POKEMON = 'ADD_POKEMON';
export const GET_POKEMON = 'GET_POKEMON';
export const UPDATE_POKEMON = 'UPDATE_POKEMON';